### ISSUE TITLE
Styled components

### ISSUE THREAD

**Issue by finnhodgkin** [fac-13/SBSHS#27]
I haven't worked with React in a little while (all about Elm Elm ELM :deciduous_tree: ) but when I did I found styled components to be the friendliest of the CSS systems. Syntactically it's very similar to SASS but allows for really easy prop-based dynamic css changes.

It's definitely a personal preference thing but if you haven't tried it out on a project yet I would thoroughly recommend it.

(However I do __not__ recommend tachyons __with__ styled components. I am not a fan of that. At all.)

**Comment by isnotafunction** [comment]
We rewrote everything using styled components and it made such a difference! Thanks for the suggestion

**Comment by finnhodgkin** [comment]
Yay
